### ISSUE TITLE
Pluriel "Liste des auteur·rice" sur Widget

### ISSUE THREAD

**Issue by jemattarde** [franck-paul/authorMode#4]
Bonjour,
Dans la vue publique du widget, le pluriel de la forme inclusive est sabré. Côté administration, c'est pourtant bon.

Aussi j'aurais une demande d'évolution : 
Serait-il possible de désactiver l'affichage de ce lien "Liste des auteur.rice.s" qui me semble peu utile. En effet ce dernier renvoie vers une page contenant la liste des auteur.rice.s avec leurs flux rss (billets + commentaires) associés. On peut déjà obtenir l'abonnement aux flux rss par auteur.rice en cliquant sur le lien vers la page dédiée d'icel.le. ;-)
Gilles

**Comment by franck-paul** [comment]
La version 3.4 inclut le réglage pour l'affichage de la liste complète des auteur·ice·s

**Comment by jemattarde** [comment]
merci pour la rapidité.
Après la mise à jour vers 3.4, j'ai vidé le répertoire de cache des « templates ». Le pluriel est corrigé, mais l'option d'affichage du lien "Liste des auteur·rice·s" n'est pas visible côté administration. Dans les options de la liste, je ne vois que : "Lister seulement les auteur·rice·s de billets standards" et  "Trier la liste (ordre alphabétique)". Le premier n'a aucun effet dans mon cas.

Côté publique, le lien apparait maintenant en fin de liste. Par dépit, j'ai essayé de vider le champ "URL de la liste des auteur·rice·s :" mais cela n'a pas d'effet, la valeur "authors" est remise.

**Comment by franck-paul** [comment]
La gestion de l'affichage du lien se fait dans les réglages du widget
